app:
  timezone: 'Asia/Shanghai' # project timezone ( set to local zone if empty)
  proxyUrl: '' # proxy url for http client use
  syncAgentServiceInterval: 10s # time interval that sync agent service in registry
  syncIdlInterval: 5m # time interval that sync all idl and generate code if idl updated (0: sync disabled)

api:
  host: '0.0.0.0' # api service listening host
  port: 8089 # api service listening port

agent:
  addr: '0.0.0.0:11010' # agent service listening address
  workerNum: 1 # worker num that process sync tasks

registry:
  builtin:
    address: 'localhost:8089' # please set to api service's external address

store:
  mysql:
    addr: '127.0.0.1' # database addr
    port: '3306' # database port
    db: 'cwgo' # mysql database name
    username: 'root' # mysql username
    password: 'password' # mysql password
    charset: 'utf8mb4' # mysql database charset
  redis:
    type: 'standalone' # standalone/cluster
    standalone:
      addr: '127.0.0.1:6379' # redis address
      username: '' # redis username
      password: 'password' # redis password
      db: 1 # redis db num
    cluster:
      masterNum: 3 # redis cluster's master node num
      addrs: # addrs's len should be same with masterNum
        - ip: '127.0.0.1' # master node ip
          port: '6391' # master node port
        - ip: '127.0.0.1'
          port: '6392'
        - ip: '127.0.0.1'
          port: '6393'
      username: '' # redis username
      password: 'password' # redis password

logger:
  savePath: 'log'
  # https://pkg.go.dev/go.uber.org/zap@v1.26.0/zapcore#Encoder
  # console/json
  encoderType: 'console'
  # https://pkg.go.dev/go.uber.org/zap@v1.26.0/zapcore#LevelEncoder
  # LowercaseLevelEncoder/LowercaseColorLevelEncoder/CapitalLevelEncoder/CapitalColorLevelEncoder
  encodeLevel: 'CapitalLevelEncoder'
  # https://pkg.go.dev/go.uber.org/zap@v1.26.0/zapcore#CallerEncoder
  # ShortCallerEncoder/FullCallerEncoder
  encodeCaller: 'FullCallerEncoder'