version: '3.7'

services:
  cwgo-api:
    container_name: cwgo-api
    build:
      context: ../../../
      dockerfile: manifest/deploy/docker/Dockerfile
      args:
        TZ: 'Asia/Shanghai'
    ports:
      - "8089:8089"
    volumes:
      - "../../../api/logs:/app/logs"
      - "../../../manifest/config:/app/config"
    networks:
      - cwgo
    command: >
      api
      --server_mode dev
      --config_path config
      --static_file_path ./dist
    depends_on:
      - redis
  cwgo-agent:
    depends_on:
      - cwgo-api
    container_name: cwgo-agent
    build:
      context: ../../../
      dockerfile: manifest/deploy/docker/Dockerfile
      args:
        TZ: 'Asia/Shanghai'
    volumes:
      - "../../../agent/logs:/app/logs"
      - "../../../manifest/config:/app/config"
    networks:
      - cwgo
    command: >
      agent
      --server_mode dev
      --config_path config
  redis:
    image: redis:6.2.5
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/redis/data:/data:rw
    command: "redis-server --requirepass 121212  --appendonly yes"
    privileged: true
    restart: always
    networks:
      - cwgo
  mysql:
    image: mysql:8.0.26
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data/mysql/data:/var/lib/mysql:rw
      - ../../sql/mysql:/docker-entrypoint-initdb.d
    privileged: true
    restart: always
    networks:
      - cwgo
networks:
  cwgo:
    driver: bridge
